apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oauth-vault.fullname" . }}-vault-config
  labels:
    {{- include "oauth-vault.labels" . | nindent 4 }}
data:
  config.hcl: |
    {{ .Values.vault.config | nindent 4 }}
  config.ctmpl: |
    {{ index .Values "vault" "templates" "config.ctmpl" | nindent 4 }}
