{{- if .Values.vault.agent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oauth-vault.agentConfigmapName" . }}
  labels:
    {{- include "oauth-vault.labels" . | nindent 4 }}
data:
  config.hcl: |
    {{ .Values.vault.agent.config | nindent 4 }}
  config.ctmpl: |
    {{ index .Values "vault" "agent" "templates" "config.ctmpl" | nindent 4 }}
{{- end }}
