{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oauth-vault.agentConfigmapName" . }}
  labels:
    {{- include "oauth-vault.labels" . | nindent 4 }}
data:
  config.hcl: |
    auto_auth {
      method {
      {{- .Values.vault.config.method | nindent 8 -}}
      }
      sink "file" {
        config = {
          path = "/home/vault/sink"
        }
      }
    }

    template {
      source      = "/etc/vault/config.ctmpl"
      destination = "/vault/secrets/config.yaml"
    }

    vault {
      address = {{ .Values.vault.config.address | quote }}
    }
  config.ctmpl: |
    {{- .Values.vault.agent.template | nindent 4 }}
{{- end }}
