apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth-vault.fullname" . }}
  labels:
    {{- include "oauth-vault.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oauth-vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oauth-vault.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oauth-vault.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.oauthVault.config.path }}
          args:
            - -config={{ .Values.oauthVault.config.path }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.vault.enabled .Values.volumeMounts }}
          volumeMounts:
          {{- if .Values.vault.enabled }}
            - name: vault-secret
              mountPath: /vault/secrets
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- if .Values.vault.enabled }}
        - name: vault-agent
          image: "{{ .Values.vault.container.repository }}:{{ .Values.vault.container.tag }}"
          imagePullPolicy: {{ .Values.vault.container.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              vault agent -config=/vault/agent/config.hcl
          volumeMounts:
            - name: vault-agent
              mountPath: /vault/agent
            - name: vault-secret
              mountPath: /vault/secrets
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
        - name: vault-proxy
          image: "{{ .Values.vault.container.repository }}:{{ .Values.vault.container.tag }}"
          imagePullPolicy: {{ .Values.vault.container.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              vault proxy -config=/vault/proxy/config.hcl
          volumeMounts:
            - name: vault-proxy
              mountPath: /vault/proxy
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
        {{- end }}
      {{- if or .Values.vault.enabled .Values.volumes }}
      volumes:
      {{- if .Values.vault.enabled }}
        - name: vault-secret
          emptyDir: {}
        - name: vault-agent
          configMap:
            name: {{ include "oauth-vault.agentConfigmapName" . }}
        - name: vault-proxy
          configMap:
            name: {{ include "oauth-vault.proxyConfigmapName" . }}
      {{- end }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
