ktor:
    application:
        modules:
            - dev.westelh.ApplicationKt.module
    development: true
    deployment:
        host: localhost
        port: 8080
        watch:
            - classes

google:
    oauth:
        clientId: "$OAUTH_CLIENT_ID"
        clientSecret: "$OAUTH_CLIENT_SECRET"
        callback: "$OAUTH_CALLBACK"

vault:
    addr: "$VAULT_ADDR"
    token: "$VAULT_TOKEN"
    kv: "$VAULT_KV"

    oauth:
        client: oauth-vault
        callback: "http://localhost:8080/oidc/user/callback"
        authorizeUrl: "http://vault.example.com/ui/vault/identity/oidc/provider/default/authorize"
        accessTokenUrl: "http://vault.example.com/v1/identity/oidc/provider/default/token"
        scopes:
            - openid
            - meta
    jwt:
        issuer: "$VAULT_JWK_ISSUER"
        audience: "$VAULT_JWK_AUDIENCE"
