ktor:
    application:
        modules:
            - dev.westelh.ApplicationKt.root
            - dev.westelh.ApplicationKt.oauth
            - dev.westelh.ApplicationKt.oidc
            - dev.westelh.ApplicationKt.api
            - dev.westelh.ApplicationKt.user
    development: true
    deployment:
        host: localhost
        port: 8080
        watch:
            - classes

google:
    oauth:
        clientId: "$OAUTH_CLIENT_ID"
        clientSecret: "$OAUTH_CLIENT_SECRET"
        callback: "$OAUTH_CALLBACK"

vault:
    addr: "$VAULT_ADDR"
    token: "$VAULT_TOKEN"
    kv: "$VAULT_KV"

    oauth:
        provider: default
        client: oauth-vault
        callback: "http://localhost:8080/user/oidc/callback"
        scopes:
            - openid
            - meta
            - google

api:
    unsafe:
        enabled: false
    auth:
        jwt:
            issuer: "$VAULT_JWK_ISSUER"
            audience: "$VAULT_JWK_AUDIENCE"
